name: SimpleMoney
favicon: null
layout_spectrum: 0.3576233694329858
typography_spectrum: 0.46053
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#223770'
    - '#ffffff'
    - '#7f888f'
    - '#4c5485'
    - '#b9b7cd'
  brandStrength: 0.4622236737050116
  lightness: 0.3821601264644414
  saturation: 0.2722673264797777
  rhythmicContrast: 0.16055732197128236
purpose: []
